quickfix/quickfix

src/C++/FieldConvertors.h, src/C++/test/FieldConvertorsTestCase.cpp
The negation of INT_MIN causes an overflow. If we cast first, both cast and negation of unsigned quantity are well-defined and the result is what we expect. Fixes #82.
=> Fix overflow in IntConvertor

src/C++/FieldConvertors.h
Unit tests pass when built with...
```shell
./configure CXX=clang++ CC=clang CXXFLAGS=-fsanitize=signed-integer-overflow
```
... which would generate errors previously.
h/t @Ambal @krzysztofwos 
Fixes #82
Refs #93
=> Don't rely on c++11 while still avoiding overflow

src/C++/Dictionary.cpp, src/C++/test/DictionaryTestCase.cpp, test/Reflector.rb
1. Fix generation of NPE instead of FieldConvertError when too short day is requested by Dictionary::getDay
+ unit tests
2. Fix generation of session id in acceptance test runner for ruby 2.0
=> Fix generation of NPE instead of FieldConvertError + improve tests

src/C++/FieldMap.h, src/C++/Message.h
In `FieldMap.h` we avoid double lookup by using `lower_bound` to get an iterator to an element with a tag _not less_ than the given tag, so if the tags are not equal we can use that iterator as a hint in the subsequent insertion.
In `Message.h`, by having a non-throwing version of `getFieldPtr`, we avoid two lookups done by `isSetField` and subsequent `getFieldRef`.
=> Avoid double lookups

src/C++/DataDictionary.cpp, src/C++/DataDictionary.h, src/C++/FieldMap.h, src/C++/Message.cpp
And add non-const overloads for begin and end that return these non-const iterators
This changes QuickFIX to match the standard library containers that also supply const and non-const begin and end.
This will be a breaking change for those that rely on FieldMap::iterator and FieldMap::g_iterator to be const iterators. Within the QuickFIX codebase, this was two places.
It appears this was the intention from the start, as without these changes FieldMap::const_iterator and FieldMap::const_g_iterator were not used at all.
To fix any breaking changes, the user should change any declaration that uses FieldMap::iterator or FieldMap::g_iterator to instead use FieldMap::const_iterator or FieldMap::g_const_iterator. This should not have an impact of non-const lvalues.
=> Re-typedef FieldMap::g_iterator and FieldMap::iterator to be non-const

src/C++/DataDictionary.cpp, src/C++/DataDictionary.h, src/C++/SessionFactory.cpp, src/C++/SessionSettings.h, src/C++/test/DataDictionaryTestCase.cpp
Add option for AllowUnknownMsgFields supported in QuickFix Java. 
Updated DataDictionary member function "shouldCheckTag" to return false for all Fields < Fields::UserMin when the option is set
=> Add AllowUnknowMsgFields options to c++ library

configure.ac, src/C++/Field.h, src/C++/FieldConvertors.h, src/C++/FieldTypes.cpp, src/C++/FieldTypes.h, src/C++/Message.cpp, src/C++/Session.cpp, src/C++/Session.h, src/C++/test/FieldConvertorsTestCase.cpp, src/C++/test/SessionTestCase.cpp
Hello,
I've update the time code in Quickfix to be based on nanosecond resolution. I've also amended the way Quickfix get's time from the operating system to make clock_gettime and clock_get_time options. The new code is completely compatible with the rest of the existing code. So one can now do things like:
void Session::insertSendingTime( Header& header )
{
UtcTimeStamp now;
bool showMilliseconds = false;
if( m_sessionID.getBeginString() == BeginString_FIXT11 )
showMilliseconds = true;
else
showMilliseconds = m_sessionID.getBeginString() >= BeginString_FIX42;
header.setField( SendingTime(now, showMilliseconds && m_millisecondsInTimeStamp) ); // <— Old approach (still works fine)
//header.setField( SendingTime(now, UtcTimeStampConvertor::PRECISION::NANOSECONDS) ); // <— New approach …
=> Time code in Quickfix

UnitTest++/Makefile, configure.ac, m4/ax_check_compile_flag.m4, src/C++/DataDictionary.cpp, src/C++/Utility.h, src/C++/test/SessionTestCase.cpp, src/at.cpp
- Change old reference of std::shared_ptr to ptr::shared_ptr
- Check compile option "-std=c++0x", and only use if supported.
- Use boost::shared_ptr if std, or std::tr1
=> Minor compile tweaks to support gcc 3.4.6

src/C++/Initiator.cpp
Through a simple brute-force connect and disconnect test, I was able to cause a thread crash.
This is because m_connections can be modified by other threads while Initiator::stop is attempting to copy from it.
Making the copy take place with the mutex locked covers this hole.
There is at least one other issue with this function, however. There is a cancel that a client connection can be forcefully shut because there is nothing preventing _m_connections_ from changing once the entries are copied to _connected_. As such, a connection can be established, and not gracefully logged off before "the plug is pulled". The initiator should really have a "stopping" state that allows existing connections to be wound up, but no new ones from being created.
=> Make Initiator::stop thread-safe

spec/FIX43.xml, spec/FIX44.xml, spec/FIXT11.xml, src/C++/Message.h, src/C++/fix44/Message.h, src/C++/fixt11/Message.h, src/C++/test/MessagesTestCase.cpp
Fixes issue #134 
* Replaced component element with group element in header for FIX44.xml and FIXT11.xml
* Added member functions for add, remove and replace repeating group in header and trailer (already existed for body).
* Added unit test that serialize and deserialize message with hops repeating group set in header.
=> Use group instead of component in header

src/C++/test/FieldMapTestCase.cpp
A test in FieldMapTestCase fails in some environments.  As the pointer array was not entirely necessary,  it has been updated to be simple conditionals.  
The original code that caused the flakey test had the pointer variable accidentally included inside the 'for' loop.  Depending on the environment the test executes in, the same memory address may be used (why the test sometimes failed) or different memory addresses may be used ( why the test sometimes passed).  
Addtionally the array was removed entirely and replaced with simple conditionals as the clang++ compiler has a problem with non pointer arrays being accessed directly in the UnitTest++ macro CHECK(1, array[0]) and in the CHECK_ARRAY_EQUAL UnitTest++ macro
=> Fixes flakey test that failed due to different execution environments

UnitTest++/src/TestMacros.h, UnitTest++/src/tests/TestTestMacros.cpp
This change allows buiding and running the tests with c++11 and above.
xref: https://akrzemi1.wordpress.com/2013/08/20/noexcept-destructors/
Fixes #61, #47
=> Allow exception to be thrown in ~FixtureDtorThrows()

src/C++/SocketAcceptor.cpp
If the port is still used by another process, QF throws an exception and doesn't free `m_pServer` pointer. It also doesn't provide mechanism to free it otherwise after the exception.
=> Avoid valgrind error because of a memory leak

src/C++/test/DataDictionaryTestCase.cpp, src/C++/test/FieldConvertorsTestCase.cpp, src/C++/test/FieldMapTestCase.cpp
This PR fixes some buffer overflow errors, as mentioned in #277 .
In general, to know the bounds of a buffer (i.e., a contiguous chunk of memory), we can either (1) find a terminating value in the buffer itself (e.g., '\0' for C string), or (2) use an additional variable to indicate the size. Buffer overflows can happen if the terminating value is not properly set, or the size information is incorrect. This patch fixes those errors.
=> Fix buffer overflows when buffers are misused.

src/python/CMakeLists.txt
The linux build (with python support) happens to work without specifying `${PYTHON_LIBRARY}`, but the macOS build needs it.
=> Fix python build

.travis.yml, README.md, examples/ordermatch/test/Makefile.am, src/C++/test/Makefile.am
This is to make sure quickfix builds with a bunch of compilers.
After this is merged I will provide a second MR that enables sanitizers ASAN/TSAN/UBSAN.
=> Add more compilers to the build matrix

src/C++/Field.h
Fix gcc warning "type qualifiers ignored on function return type"
=> Change "const int" return type to plain "int"

.github/workflows/build_sln.yml, .github/workflows/build_test_autotools.yml, .github/workflows/build_test_cmake.yml, .github/workflows/build_test_sln.yml
This PR adds three pipelines to the repo, watching push and pull request events:
1. Build with Autotools ([build_test_autotools.yml](https://github.com/tarc/quickfix/blob/89981c9d8243b179bbad82d5fce966e19553887f/.github/workflows/build_test_autotools.yml)).
2. Build with CMake ([build_test_cmake.yml](https://github.com/tarc/quickfix/blob/89981c9d8243b179bbad82d5fce966e19553887f/.github/workflows/build_test_cmake.yml)).
3. Build Visual Studio Solution ([build_test_sln.yml](https://github.com/tarc/quickfix/blob/89981c9d8243b179bbad82d5fce966e19553887f/.github/workflows/build_test_sln.yml)).
They make use of the integrated GitHub actions.
As the pipelines were being developed, some "bugs" were catched:
- A copy of Except.h was missing for WIN32 builds from cmake/QuickfixPrebuildSetup.cmake. …
=> Add GitHub pipelines

src/C++/FieldConvertors.h, src/C++/test/FieldConvertorsTestCase.cpp
This patch fixes a buffer overflow issue, as illustrated in #229 
It is caused by unbounded precision input when converting time to string. The buffer only supports a maximum of 9 chars, and thus buffer overflow happens if the input precision is greater than 9 (i.e., upper bound). This solution is to set precision to the lower (upper) bound when it underflows (overflows).
=> Fix buffer overflow by making precision bounded.

configure.ac, src/C++/Utility.h
I wasn't being able to compile the project on CentOS 7.5 with `cmake` because of a missing condition in the *src/C++/Utility.h* file.
This PR fixes two things:
- A wrong `HAVE_STD_TR1_SHARED_PTR` condition where it was including `<tr1/memory>` instead of just `<memory>`
- Adds the missing `HAVE_STD_TR1_SHARED_PTR_FROM_TR1_MEMORY_HEADER` condition to include `<tr1/memory>` and use the namespace `ptr = std::tr1`
---------------
The solution is based on the content of the file *cmake/FindSharedPtr.cmake*:
This is the condition to set the `HAVE_STD_TR1_SHARED_PTR` variable:
```
check_cxx_source_compiles("#include <memory>
int main() {
std::shared_ptr<int> int_ptr;
return 0;
}"
HAVE_SHARED_PTR_IN_STD_NAMESPACE)
```
And this is the one to set `HAVE_STD_TR1_SHARED_PTR_FROM_TR1_MEMORY_HEADER`: …
=> Fix conditional inclusion of headers and namespace for shared_ptr

src/C++/FieldConvertors.h, src/C++/test/FieldConvertorsTestCase.cpp
Fixes an Visual Studio Compilation issue in the FieldConvertors.h header file. Visual Studio compilation has stricter rules on dynamic arrays
=> FieldConvertors Visual Studio Compilation Fix

src/C++/HttpConnection.cpp, src/C++/HttpConnection.h, src/C++/SocketConnection.cpp, src/C++/SocketConnection.h, src/C++/SocketMonitor.cpp, src/C++/SocketMonitor.h, src/C++/ThreadedSocketConnection.cpp, src/C++/ThreadedSocketConnection.h, src/C++/TimeRange.cpp, src/C++/TimeRange.h, src/C++/test/TimeRangeTestCase.cpp
Switching to `poll` instead of `select` for polling sockets, in order to get around the size limit of `FD_SET` (1024).
Code adapted from: https://github.com/s10i/quickfix
=> Using `poll` instead of `select` for sockets

doc/html/configuration.html
Fix the default value of PersistMessages in doc. It's [set to Y by default](https://github.com/quickfix/quickfix/blob/b7c346f81a772ada7dd0bb0ea7b6a0962c8cec69/src/C%2B%2B/Session.cpp#L62), but the doc says it's N. 
Also Valid values in current version is Y<br>Y, which should be Y<br>N.
=> Doc update - PersistMessages is Y by default

src/C++/Session.cpp, src/C++/Session.h, src/C++/test/SessionTestCase.cpp
Extract logic for determining is a FIX session can support sub second timestamps. Added unit tests.
=> Extract and test sub second precision

src/C++/Session.cpp
This commit addresses an error reported by a user that has migrated
their platform from QF/J to QF/C++:
- If Resend is requested
- With an EndSeqNo specified (i.e. EndSeqNo is not
zero/infinity)
- And EndSeqNo is greater than the MsgSeqNum at the end of
the Resend
- And the last message resent was an app-level message
- Then the SequenceReset-GapFill message sent after the last resent app-level
message will have the same MsgSeqNum as that last app-level message
- Which is an error: the seqnum should be the same MsgSeqNum + 1
One way to reproduce this is to send app-level messages while the
counterparty is not logged on, causing them to be queued for send, and
to advance the seqnums forward causing a gap (e.g. in the case of a
failover where seqnums are advanced to mitigate duplication). …
=> Add QF/J's 'appMessageJustSent' logic for Resend

src/C++/SSLSocketAcceptor.cpp, src/C++/SSLSocketAcceptor.h, src/C++/SSLSocketInitiator.cpp, src/C++/SSLSocketInitiator.h, src/C++/ThreadedSSLSocketAcceptor.cpp, src/C++/ThreadedSSLSocketAcceptor.h, src/C++/ThreadedSSLSocketInitiator.cpp, src/C++/ThreadedSSLSocketInitiator.h, src/C++/Utility.cpp, src/C++/Utility.h, src/C++/UtilitySSL.cpp, src/C++/UtilitySSL.h
Solves issue #272. SSL Private key password is now properly read, when having multiple instances of Initiator/Acceptor
**Change summary:**
1. Added additional parameter `passwordCallbackParam` to the following functions:
- readPrivateKey
- readX509
- loadSSLCert
*Files: UtilitySSL.cpp/h*
2. The classes that use `loadSSLCert()` have been modified to pass `this` in the newly added `passwordCallbackParam`. This parameter will be wired by OpenSSL to the static callback method `passPhraseHandleCB()` as the forth argument.  The argument is of type `void*`, so it is cast to the appropriate class type and call to the member method `passwordHandleCallback`
*Files: SSLSocketAcceptor.cpp/h, SSLSocketInitiator.cpp/h, ThreadedSSLSocketAcceptor.cpp/h ThreadedSSLSocketInitiator.cpp/h*
---
Solves issue …
=> Fix: private key password now read from proper instance & SSL Connection Fix

spec/Values.xsl, spec/generate_c++.sh
NoSides is the only NUMINGROUP field that has enum values. The
code generator was generating chars for those values instead of ints.
This commit causes the generator to use int instead of char if the type
is NUMINGROUP (again, only affects NoSides currently).
Also, the sh version of the c++ generate script was not actually generating
FixValues.h and FixTValues.h (but the bat version was).
=> NoSides values in FixValues.h are int not char

src/C++/FieldConvertors.h, src/C++/test/FieldConvertorsTestCase.cpp
Instead of ignoring/allowing Int fields to overflow, detect this
condition and raise an exception (which will trigger a Reject).
=> Detect overflow in IntConvertor, send Reject

src/C++/SSLSocketAcceptor.cpp, src/C++/SSLSocketConnection.cpp, src/C++/SSLSocketConnection.h, src/C++/SSLSocketInitiator.cpp, src/C++/SSLSocketInitiator.h
SSLSocketInitiator: Added timeout for SSL handshake, removed ssl handhake spinloop
SSLSocketAcceptor: removes socket from monitor if accept ssl fails
SSLConnection: processQueue and readFromSocket now will exit if they are waiting for data to be read/written first.
Addresses #397, #398
=> SSLSocketInitiator timeout fix, SSLSocketAcceptor monitor fix

src/C++/UtilitySSL.cpp, src/C++/UtilitySSL.h
Only RSA and DSA keys are currently allowed. This allows EC keys to be used too.
=> Enable use of eliptic curve client certs

src/C++/SSLSocketAcceptor.cpp, src/C++/SSLSocketInitiator.cpp
sockets create in
```cpp
// SSLSocketInitiator.cpp line 300
socket_handle result = m_connector.connect( address, port, m_noDelay, m_sendBufSize, m_rcvBufSize, sourceAddress, sourcePort );
```
if set
```cpp
// SSLSocketInitiator.cpp line 309
BIO *sbio = BIO_new_socket(result, BIO_CLOSE); //unfortunately OpenSSL assumes socket is int
```
will cause socket to be closed twice
1. first close
```cpp
// SocketMonitor.cpp line 108
socket_close( s );
// call stack
// SSLSocketInitiator::onDisconnect				SSLSocketInitiator.cpp
// SSLSocketConnection::disconnect				SSLSocketConnection.cpp
// SocketMonitor::drop						SocketMonitor.cpp
// socket_close							Utility.cpp
// close
```
2. second close
```cpp
// SSLSocketConnection.cpp line 160
SSL_free(m_ssl);
// call stack
// …
```
=> fix double close socket

CMakeLists.txt, cmake_config.h.in, src/C++/DataDictionary.cpp, src/C++/Message.cpp, src/C++/Message.h, src/C++/Session.cpp
Looks like there was quite a bit of code in the core library objects (DataDictionary, Message, Session) pertaining to a specific exchange. This isn't an appropriate place for exchange customization.
=> Remove custom code for EMX exchange

src/C++/Exceptions.h, src/pt.cpp
Validation in performance tests were failing because we now properly validate the presence of header and trailer fields
=> Generate BodyLength and CheckSum when testing validation performance

src/C++/Utility.cpp
We monitor fix session logs during the Quickfix run and cannot open the file *.body for the C++ version of Quickfix on Windows. Because the file is locked.
We do not have the same problems with the .NET version of Quickfix.
The fix allows you to view the file during the Quickfix run.
=> Allow opening log file in another application when quickfix is running

src/C++/Session.cpp
On construction, state needs to be reset if we are outside of the session time. However calling the reset method on session also calls disconnect and attempts to login. Instead we must only reset the state without additional side effects.
=> Only reset state on session construction

src/C++/SharedArray.h
List of changes:
1. Call destructor without namespace (as at https://github.com/quickfix/quickfix/blob/master/src/C%2B%2B/SharedArray.h#L172 ) - it causes a compilation error in gcc-12 and clang-15;
2. Correct copy constructor: if `m_pCtr` is left uninitialized, `release()` will crash because of accessing `m_pCtr` in `decrement_reference_count()`.
=> SharedArray: crash on arm64

src/C++/Field.h, src/C++/FieldConvertors.h, src/C++/FieldTypes.h, src/C++/test/FieldConvertorsTestCase.cpp, src/python/quickfix.py, src/ruby/QuickfixRuby.cpp
Adding a distinct Int64Field to ensure proper transfer of large integers whatever the platform is. Integer conversions has been implemented (src/C++/FieldConvertors.h) as a template to support multiple precisions (tests have been added for each potential case). For Windows, scope of pragma(warning(disable:4146)) has been reduced to the absolutely necessary minimum to avoid accidental masking of other potential issues to fix.
=> Adding Int64Field.

NEWS, doc/html/configuration.html, src/C++/HttpConnection.cpp, src/C++/Session.cpp, src/C++/Session.h, src/C++/SessionFactory.cpp, src/C++/SessionSettings.h, src/C++/test/SessionTestCase.cpp
- Implementation of "Using NextExpectedMsgSeqNum(789) to synchronize a FIX session" as described in the FIX technical specification: https://www.fixtrading.org/standards/fix-session-layer-online/#extended-features-for-fix-session-and-fix-connection-initiation
- new boolean parameter: SendNextExpectedMsgSeqNum
- closes #146 
- closes #347
=> Using NextExpectedMsgSeqNum(789) to synchronize a FIX session

src/C++/FieldConvertors.h
clang prints warning:
```
./FieldConvertors.h:253:54: warning: overflow in expression; result is -2147483648 with type 'int' [-Winteger-overflow]
253 |       if( nx > typename std::make_unsigned<T>::type( -VALUE_MIN ) )
./FieldConvertors.h:253:54: warning: overflow in expression; result is -9223372036854775808 with type 'long' [-Winteger-overflow]
253 |       if( nx > typename std::make_unsigned<T>::type( -VALUE_MIN ) )
```
Current PR performs casting signed to unsigned and then negation. It is defined behaviour:
```
[conv.integral]
If the destination type is unsigned, the resulting value is the least unsigned integer congruent to the source
integer (modulo 2^n where n is the number of bits used to represent the unsigned type). [ Note: In a two’s
complement representation, this conversion …
```
=> FieldConvertors: warning caused by signed integer overflow

src/C++/Session.cpp, src/C++/test/SessionTestCase.cpp
Current behaviour: QuickFIX increments expected target MsgSeqNum only if persisting is enabled.
Correct behaviour (I think): expected target MsgSeqNum should be incremented on each received correct message.
Corresponding code from other FIX implementations:
- QuickFIX/j: No return statement in case of disabled persisting: https://github.com/quickfix-j/quickfixj/blob/master/quickfixj-core/src/main/java/quickfix/Session.java#L1374
- QuickFIX/go: https://github.com/quickfixgo/quickfix/blob/main/in_session.go#L213
=> Handle ResendRequest: update target MsgSeqNum regardless of message persisting

src/C++/Utility.h
The existing type definition conflicts with Python39\include\pyconfig.h type definition for `ssize_t`, causing
`C2371: 'ssize_t': redefinition; different basic types`
I propose we use the same way of defining type for ssize_t as in pyconfig.h
=> Making ssize_t definition aligned with ssize_t type in Python 3.9

m4/ax_lib_ssl.m4, src/C++/test/UtilityTestCase.cpp
Environment: Ubuntu 20.04, autoreconf (GNU Autoconf) 2.71
./bootstrap script produces warning:
`+ autoreconf -i -Wall
configure.ac:34: warning: AC_CHECK_HEADERS("$with_openssl/include/openssl/ssl.h"): you should use literals
./lib/autoconf/headers.m4:217: AC_CHECK_HEADERS is expanded from...
`
The proposed patch fixes that warning.
=> Fix AC_CHECK_HEADERS warning for autotools build

src/C++/MessageSorters.h, src/C++/test/MessageSortersTestCase.cpp
At the current moment, all trailer fields are sorted by their id (the less id, the less position). Signature is a DATA field but in contrary to all other DATA fields, its length field is not 1 less that the DATA field id but larger (93 vs. 89). Hence, SignatureLength is put after Signature by FieldMap::addField. On the other hand, Message::extractField is used to process fields one-by-one through the coming message. Thus, SignatureLength is never found because it is not processed yet because it comes after Signature. Missing DATA length field is treated as an error now so a Signature field always leads to an error in message processing.
The suggested fix puts SignatureLength as the first field in the trailer.
No attempt to define specific comparison rules between Signature and …
=> Fixing the sorting order of trailer's FIELD::SignatureLength

src/C++/Session.h
Refresh the session when a new connection is established so that It won't be reseted [here](https://github.com/ilolis/quickfix/blob/d6d0f11a4024dcc296a2ccece9211fc7de54a5cb/src/C%2B%2B/Session.h#L237).
Fixes #540, so please feel free to read #540 for a more detailed description of the bug.
=> Refresh the Session state when new connection is established before the Session reset checks occur

cmake/QuickfixPrebuildSetup.cmake, cmake_config.h.in, src/C++/MySQLLog.cpp, src/C++/PostgreSQLLog.cpp
Without this change, `HAVE_*SQL` compile definition are never passed to C/C++ code when building with cmake.
You can check it with following command:
```sh
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DHAVE_SSL=ON -DHAVE_MYSQL=ON -DHAVE_POSTGRESQL=ON ..
make -j32
strings src/C++/libquickfix.so | grep MySQLStoreFactory
```
Without the fix:
```
❯ strings src/C++/libquickfix.so | grep MySQLStoreFactory | wc -l                                                                      
0
```
With the fix:
```
❯ strings src/C++/libquickfix.so | grep MySQLStoreFactory | wc -l
47
```
I also fix various deprecation warning / example build error.
=> Fix cmake SQL store never build

src/C++/pugixml.cpp
- Replaced multiple instances of deprecated 'sprintf' function with the safer 'snprintf' alternative in pugixml.cpp.
- The change eliminates compiler warnings and improves code security by preventing potential buffer overflows.
Warnings Addressed:
- pugixml.cpp:3656
- pugixml.cpp:3664
- pugixml.cpp:3672
- pugixml.cpp:3686
- pugixml.cpp:3694
- pugixml.cpp:6843
=> Replace deprecated sprintf with snprintf in pugixml.cpp

src/C++/SessionSettings.h, src/C++/UtilitySSL.cpp, src/C++/UtilitySSL.h
Hello,
TLS 1.3 is officially supported by OpenSSL [since the version 1.1.1 (11 Sep 2018)](https://www.openssl.org/news/openssl-1.1.1-notes.html). The support of this new protocol comes with a new OpenSSL API to set the ciphers.
There is now two functions that are available that can be used to set the ciphers.
* `SSL_CTX_set_cipher_list`: sets the list of available ciphers (TLSv1.2 and below). This function does not impact TLSv1.3 ciphersuites.
* `SSL_CTX_set_ciphersuites`: is used to configure the available TLSv1.3 ciphersuites (an mayber upper version of TLS too). 
I found the rationale of this new OpenSSL API in a GitHub comment here: https://github.com/openssl/openssl/issues/13704#issuecomment-748950174. It is stated the following:
* `[...] You cannot enable/disable TLSv1.3 …
=> Add support of TLS 1.3 (and add TLSCipherSuites setting)

src/C++/test/DataDictionaryTestCase.cpp, src/C++/test/SessionTestCase.cpp
This PR resolves warning:
```
In constructor ‘Catch::BinaryExpr<LhsT, RhsT>::BinaryExpr(bool, LhsT, Catch::StringRef, RhsT) [with LhsT = int; RhsT = int]’,
inlined from ‘std::enable_if_t<((bool)std::conjunction<Catch::Detail::is_eq_comparable<LhsT, RhsT, void>, std::is_arithmetic<RhsT> >::value), Catch::BinaryExpr<LhsT, RhsT> > Catch::operator==(ExprLhs<LhsT>&&, RhsT) [with RhsT = int; LhsT = int]’ at catch_amalgamated.hpp:5576:9,
inlined from ‘void CATCH2_INTERNAL_TEST_0()’ at DataDictionaryTestCase.cpp:168:5:
catch_amalgamated.hpp:5446:13: warning: ‘delim’ may be used uninitialized [-Wmaybe-uninitialized]
5446 |             m_rhs( rhs )
|             ^~~~~~~~~~~~
DataDictionaryTestCase.cpp: In function ‘void CATCH2_INTERNAL_TEST_0()’:
DataDictionaryTestCase.cpp:164:9: note: ‘delim’ was …
```
=> Tests: DataDictionaryTestCase warning, SessionTestCase null pointer dereference

src/C++/FieldConvertors.h
Existing code contains an undefined behaviour because `unsigned x` is casted to `T = signed`, then negated (undefined behaviour) and then implicitly casted back to `unsigned` (line 260).
This PR removes an undefined behaviour of negation of signed int, replacing with defined behaviour of unsigned negation.
The bug can be reproduced with gcc-14 (arm64):
```
FieldConvertorsTestCase.cpp:390: FAILED:
CHECK( MIN_INT == IntConvertor::convert( "-2147483648" ) )
with expansion:
-2147483648 == -2147483648
```
From C++ standard:
```
[expr.unary.op]
The negative of an unsigned quantity is computed by subtracting its value from 2^n, where n is the number of bits in the promoted operand.
```
@pps314159 May you please check, is MSVC warning suppression still required?
=> FieldConvertors: avoid undefined behaviour on signed negation

src/C++/double-conversion/utils.h
Compiling the quickfix failed for loong64 in the Debian Package Auto-Building environment.
The error log is as follows,
```
In file included from ./double-conversion/diy-fp.h:31,
from double-conversion/diy-fp.cc:29,
from FieldConvertors.cpp:37:
./double-conversion/utils.h:84:2: error: #error Target architecture was not detected as supported by Double-Conversion.
84 | #error Target architecture was not detected as supported by Double-Conversion.
|  ^~~~~
......
```
The Full log can be found at https://buildd.debian.org/status/logs.php?pkg=quickfix&ver=1.15.1%2Bdfsg-4.1&arch=loong64.
I have built successfully on my local ENV.
Please review.
=> Add support for loongarch64

cmake_config.h.in, src/C++/UtilitySSL.cpp, src/C++/UtilitySSL.h
Add a missing `#endif` in `UtilitySSL.h`,
Fix a typo in `UtilitySSL.cpp` -- `TLSCipherSuites` -> `TLS_CIPHER_SUITES`
Add the `HAVE_SSL` macro to `cmake_config.h.in`, as without this, no cmake build ever has SSL support.
=> Fix build with HAVE_SSL

src/C++/Log.cpp, src/C++/Log.h
This commit modernizes the C++ logging classes by making use of the 'default' keyword for destructors, adopting the explicit keyword, improving the precision of the 'override' keyword, and optimizing memory usage through the use of 'std::move()'. The addition of preprocessor definitions in 'config.h' further improves the code's platform compatibility.
=> Refactor and modernize C++ log classes

src/C++/SSLSocketInitiator.cpp, src/C++/SocketInitiator.cpp, src/C++/ThreadedSSLSocketInitiator.cpp, src/C++/ThreadedSocketInitiator.cpp
This pull request to fix following issue
https://github.com/quickfix/quickfix/issues/604
Expected: ReconnectInterval value in [SESSION] dominates the value in [DEFAULT]
Bug: currently Initiator use ReconnectInterval value in [DEFAULT].
I'm sure that my solution can fix for an initiator (SocketInitiator, SSLSocketInitiator, ThreadedSSLSocketInitiator) but I'm not sure about an acceptor.
=> ReconnectInterval value in [SESSION] dominates the value in [DEFAULT]

src/C++/SessionFactory.cpp
This pull request to fix following issue
https://github.com/quickfix/quickfix/issues/615
On setting: MillisecondsInTimeStamp=N
Expected: in FIX message, Date-Time format will be YYYMMDD-HH:MM:SS (20241125-16:49:49), without fractional part of seconds.
Bug: Date-Time format still shows in milliseconds.
=> MillisecondsInTimeStamp=N config
